core/urls.py
from argparse import Namespace
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
import account
from account.views import home_page

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', home_page, name='home'),
    path('account/', include('account.urls', namespace='user')),
    path('post/', include('feed.urls', namespace='post')),
    path('users/', include('users.urls', namespace='users')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feed/urls.py
from django.urls import path
from django.conf.urls import handler404, handler500
from feed.views import create_post, post_list, post_details


app_name = 'post'
urlpatterns = [
    path('',post_list, name='post_list'),
    path('<int:pk>/',post_details,name='post_detail'),
    path('create/',create_post,name='create_post'),

]

feed/models.py
from django.db import models
from account.models import User
from django.urls import reverse
from django.utils import timezone

class Post(models.Model):
    DISPLAY_POST_CHOICES = (
        ('everyone', 'Everyone'),
        ('friends', 'Friends'),
    )
    
    title = models.CharField(max_length=255)
    img = models.ImageField(upload_to='post/imges/', default='post/imges/blog-img.png')
    description = models.CharField(max_length=255, blank=True)
    display_post = models.CharField(max_length=10, choices=DISPLAY_POST_CHOICES, default='everyone')
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
	# tags = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.description


    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

feed/forms.py
from django import forms
from .models import Post

class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','img','description', 'display_post']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({
        'placeHolder': 'Post title',
        'class': ' w-full px-4 py-2 mt-2 text-md placeholder-gray-400 focus:outline-none border border-blue-500 focus:ring-1 focus:ring-blue-700 focus:ring-opacity-50 rounded-md'
        })
        self.fields['img'].widget.attrs.update({
        'placeHolder': 'Post image',
        'class': 'w-full px-4 py-2 mt-2 text-md placeholder-gray-400 focus:outline-none border border-blue-500 focus:ring-1 focus:ring-blue-700 focus:ring-opacity-50 rounded-md'
        })
        self.fields['description'].widget.attrs.update({
        'placeHolder': 'Post contents',
        'class': ' w-full px-4 py-2 mt-2 text-md placeholder-gray-400 focus:outline-none border border-blue-500 focus:ring-1 focus:ring-blue-700 focus:ring-opacity-50 rounded-md'
        })
        self.fields['display_post'].widget.attrs.update({

        'placeHolder': 'Status',
        'class': ' w-full px-4 py-2 mt-2 text-md placeholder-gray-400 focus:outline-none border border-blue-500 focus:ring-1 focus:ring-blue-700 focus:ring-opacity-50 rounded-md'
        })

feed/views.py
from cProfile import Profile
from operator import ipow
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from feed.forms import NewPostForm
from feed.models import Post
from account.models import User

@login_required
def create_post(request):
	user = request.user
	if request.method == "POST":
		form = NewPostForm(request.POST, request.FILES)
		if form.is_valid():
			data = form.save(commit=False)
			data.author = user
			data.save()
			return redirect('post:post_list')
	else:
		form = NewPostForm()
	return render(request, 'feed/create_post.html', {'form':form})

def post_list(request):
    posts = Post.objects.all()
    user = User.objects.get(phone = request.user.phone)
    user_friends = user.profile.friends.all()
    friend_list = []
    for friend in user_friends:
        friend_list.append(friend)
        
    print('\n\n', friend_list)
    
    context = {
        'posts' : posts,
        'friend_list':friend_list,
    }
    return render(request, 'feed/post_list.html', context)
def post_details(request, pk):
    post = get_object_or_404(Post, pk=pk)
    
    context = {
        'post' : post,
        
    }
    
    return render(request,'feed/post_details.html', context)
    

feed/templates/feed/create_post.html
{% extends 'account/home.html' %}

{% block contents %}
<section class=" py-20 lg:py-[120px] overflow-hidden relative z-10">
    <div class="container mx-auto">
        <div class="flex flex-wrap lg:justify-between -mx-36 shadow-md">
          
            <div class="w-full md:w-1/2 lg:w-9/12 xl:w-7/12 px-1 mx-auto my-auto ">
                <div class="bg-white relative rounded-lg p-8 sm:p-12 border-4 shadow-lg">
                    <h1 class='text-xl text-gray-700 font-bold text-center pb-4'>Write your post </h1>
                    <form method='post' enctype="multipart/form-data">
                        {% csrf_token %}

                        {% if form.errors %}
                                {% if form.non_field_errors %}
                                <div class="bg-red-100 rounded-lg py-5 px-6 mb-3 text-base text-red-700 inline-flex items-center w-3/5" role="alert">
                                    <img src="https://cdn-icons.flaticon.com/png/512/4201/premium/4201973.png?token=exp=1643782418~hmac=5d46005c897e27ca8f6cad6a2956f765" alt="alert-img" class="w-12 h-12 pr-6">
                                    {{form.non_field_errors|striptags}}
                                  </div>
                                {% endif %}
                                {% for field in form %}
                                {% if field.errors %}
                                <div class="bg-red-100 rounded-lg py-5 px-6 mb-3 text-base text-red-700 inline-flex items-center w-3/5" role="alert">
                                    <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="times-circle" class="w-4 h-4 mr-2 fill-current" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                                      <path fill="currentColor" d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm121.6 313.1c4.7 4.7 4.7 12.3 0 17L338 377.6c-4.7 4.7-12.3 4.7-17 0L256 312l-65.1 65.6c-4.7 4.7-12.3 4.7-17 0L134.4 338c-4.7-4.7-4.7-12.3 0-17l65.6-65-65.6-65.1c-4.7-4.7-4.7-12.3 0-17l39.6-39.6c4.7-4.7 12.3-4.7 17 0l65 65.7 65.1-65.6c4.7-4.7 12.3-4.7 17 0l39.6 39.6c4.7 4.7 4.7 12.3 0 17L312 256l65.6 65.1z"></path>
                                    </svg>
                                    {{field.name}}:{{field.errors|striptags}}
                                  </div>
                                {% endif %}{% endfor %}{% endif %}
                                {{form.media}}
                                {{form.as_p}}
                        {% comment %} {{form.title}}
                        
                        {{form.body}}
                        {{form.status}} {% endcomment %}
                        <div class="my-4">
                            <button type='submit' class="bg-green-500 text-green-300 font-bold rounded border-b-2 border-green-500 hover:border-green-600 hover:bg-green-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center">
                              <span class="px-2 py-1">Submit</span>
                            </button>
                          </div>
                        
                        
                    </form>

                </div>
            </div>
        </div>
    </div>
</section>

{% endblock contents %}

feed/templates/feed/post_details.html
{% extends 'account/home.html' %}


{% block contents %}

<!-- component -->
{% comment %} <div class="mt-16 relative px-auto w-full h-60 overflow-hidden">
  <a class="  text-red-400 hover:text-red-500" href="{% url 'blog:post_list'%}">Back</a>
  <a class=" px-8 text-red-400 hover:text-red-500" href="share">Share post</a>
</div> {% endcomment %}

<main class="relative container mt-24 mx-auto bg-white px-4">
  <div class="mt-16 relative px-auto w-full h-full overflow-hidden">
    <img class=" w-4/5  mx-auto py-8 text-justify"
      src="{{post.img.url}}"
      alt="post-img" />
  </div>

  <article class="w-4/5 mx-auto py-8 text-justify">
    <h1 class="text-2xl font-bold">{{ post.title }}</h1>
    <h2 class="mt-2 text-sm text-gray-500">{{ post.author.first_name }}, <span class="px-2">{{ post.date_posted|date }}</span></h2>

    <p class="mt-4">{{post.description|safe}}</p>
   
  </article>
</main>

{% endblock contents %}

feed/templates/feed/post_list.html
{% extends 'account/home.html' %}
{% load static %}



{% block contents %}

<div class="container mx-auto mt-12">

    <div
        class="relative rounded-lg flex flex-col md:flex-row items-center  mx-2  ">
        <a href="{% url 'post:create_post'%}"
            class="bg-gray-100 text-gray-800 font-bold rounded hover:border-gray-300 hover:bg-gray-200 hover:text-gray-900  py-2 px-6 inline-flex items-center">
            <span class="mr-2">Create New Post</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                <path fill="currentcolor" d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"></path>
            </svg>
        </a>
    </div>
</div>
{% if posts %}
{% for post in posts %}



<!--test-->



<!--test-->


<!-- post-list-component set for everyone -->
{% if post.display_post == 'everyone' %}
<div class="container mx-auto my-12 ">

    <div
        class="relative rounded-lg flex flex-col md:flex-row items-center md:shadow-lg md:h-80 mx-2 border-2 hover:shadow-xl">

        <div
            class="z-0 order-1 md:order-2 relative w-full md:w-2/5 h-80 md:h-full overflow-hidden rounded-lg md:rounded-none md:rounded-r-lg">
            <div class="absolute inset-0 w-full h-full object-cover object-center bg-gray-300 bg-opacity-30 bg-contain bg-center bg-no-repeat"
                style="background-image: url( {{post.img.url}} ); background-blend-mode: multiply;"></div>
            <div
                class="md:hidden absolute inset-0 h-full p-6 pb-6 flex flex-col-reverse justify-start items-start bg-gradient-to-b from-transparent via-transparent to-gray-900">

                <h3 class="w-full font-bold text-2xl text-white leading-tight mb-2">{{post.title|truncatewords:10}}</h3>
                <h4 class="w-full text-xl text-gray-100 leading-tight">{{post.author}}</h4>
            </div>
            <svg class="hidden md:block absolute inset-y-0 h-full w-24 fill-current text-white -ml-12"
                viewBox="0 0 100 100" preserveAspectRatio="none">
                <polygon points="50,0 100,0 50,100 0,100" />
            </svg>
        </div>

        <div class="z-10 order-2 md:order-1 w-full h-full md:w-3/5 flex items-center -mt-6 md:mt-0">
            <div
                class="p-8 md:pr-18 md:pl-14 md:py-12 mx-2 md:mx-0 h-full bg-white rounded-lg md:rounded-none md:rounded-l-lg shadow-xl md:shadow-none ">

                <h3 class="hidden md:block font-bold text-2xl text-gray-700">{{post.title|truncatewords:15}}</h3>
                <h4 class="text-blue-600 hidden md:block text-md text-blue-600 my-1">Author: <span
                        class="px-2">{{post.author.first_name}}</span></h4>

                <span class="text-blue-600 text-md">Created on:<span class="px-2">{{post.date_posted|date}}</span></span>
                
                <h2 class="my-4 text-gray-600 text-justify ">{{post.description|safe|truncatewords:25}}</h2>
                <a class="flex items-baseline mt-3 text-blue-600 hover:text-blue-900 focus:text-blue-900"
                    href="/post/{{post.pk}}/">
                    <span>Read more</span>
                    <span class="text-xs ml-1">&#x279c;</span>
                </a>
            </div>
        </div>
    </div>
    
</div>
{% endif %}
<!-- end-post-component for everyone-->

<!-- post-list-component set for friends -->
{% for friend in friend_list %}
{% if post.author.first_name in friend.user.first_name %}

<div class="container mx-auto my-12 ">

    <div
        class="relative rounded-lg flex flex-col md:flex-row items-center md:shadow-lg md:h-80 mx-2 border-2 hover:shadow-xl">

        <div
            class="z-0 order-1 md:order-2 relative w-full md:w-2/5 h-80 md:h-full overflow-hidden rounded-lg md:rounded-none md:rounded-r-lg">
            <div class="absolute inset-0 w-full h-full object-cover object-center bg-gray-300 bg-opacity-30 bg-contain bg-center bg-no-repeat"
                style="background-image: url( {{post.img.url}} ); background-blend-mode: multiply;"></div>
            <div
                class="md:hidden absolute inset-0 h-full p-6 pb-6 flex flex-col-reverse justify-start items-start bg-gradient-to-b from-transparent via-transparent to-gray-900">

                <h3 class="w-full font-bold text-2xl text-white leading-tight mb-2">{{post.title|truncatewords:10}}</h3>
                <h4 class="w-full text-xl text-gray-100 leading-tight">{{post.author}}</h4>
            </div>
            <svg class="hidden md:block absolute inset-y-0 h-full w-24 fill-current text-white -ml-12"
                viewBox="0 0 100 100" preserveAspectRatio="none">
                <polygon points="50,0 100,0 50,100 0,100" />
            </svg>
        </div>

        <div class="z-10 order-2 md:order-1 w-full h-full md:w-3/5 flex items-center -mt-6 md:mt-0">
            <div
                class="p-8 md:pr-18 md:pl-14 md:py-12 mx-2 md:mx-0 h-full bg-white rounded-lg md:rounded-none md:rounded-l-lg shadow-xl md:shadow-none ">

                <h3 class="hidden md:block font-bold text-2xl text-gray-700">{{post.title|truncatewords:15}}</h3>
                <h4 class="text-blue-600 hidden md:block text-md text-blue-600 my-1">Author: <span
                        class="px-2">{{post.author.first_name}}</span></h4>

                <span class="text-blue-600 text-md">Created on:<span class="px-2">{{post.date_posted|date}}</span></span>
                
                <h2 class="my-4 text-gray-600 text-justify ">{{post.description|safe|truncatewords:25}}</h2>
                <a class="flex items-baseline mt-3 text-blue-600 hover:text-blue-900 focus:text-blue-900"
                    href="/post/{{post.pk}}/">
                    <span>Read more</span>
                    <span class="text-xs ml-1">&#x279c;</span>
                </a>
            </div>
        </div>
    </div>
    
</div>

{% endif %}
{% endfor %}
<!-- end-post-component -->


{% endfor %}
{% else %}
<div class="z-10 order-2 md:order-1 w-full h-full md:w-3/5 flex items-center -mt-6 md:mt-0">
    <div
        class="p-8 md:pr-18 md:pl-14 md:py-12 mx-2 md:mx-0 h-full bg-white rounded-lg md:rounded-none md:rounded-l-lg shadow-xl md:shadow-none ">

        <h3 class="hidden md:block font-bold text-2xl text-gray-700">No One has posted anything yet!</h3>
        
    </div>
</div>

{% endif %}



{% endblock contents %}