core/urls.py
from argparse import Namespace
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
import account
from account.views import home_page

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', home_page, name='home'),
    path('account/', include('account.urls', namespace='user')),
    path('post/', include('feed.urls', namespace='post')),
    path('users/', include('users.urls', namespace='users')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.conf.urls import handler404, handler500
from users import views as user_views


app_name = 'users'
urlpatterns = [
    path('', user_views.users_list, name='users_list'),
    path('profile/',user_views.my_profile, name='profile'),
	path('<int:phone>/', user_views.profile_view, name='profile_view'),
	path('friends/', user_views.friend_list, name='friend_list'),
    path('friend-request/send/<int:id>/', user_views.send_friend_request, name='send_friend_request'),
    path('friend-request/accept/<int:id>/', user_views.accept_friend_request, name='accept_friend_request'),
    path('search_users/', user_views.search_users, name='search_users'),
    path('search/', user_views.search_api, name='search'),
]

users/models.py
from email.policy import default
from django.db import models
from account.models import User
from django.urls import reverse
from django.utils import timezone
from django.db.models.signals import post_save
from django.conf import settings
from autoslug import AutoSlugField

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default_avatar.png', upload_to='profile/avatar/')
    slug = AutoSlugField(populate_from='user')
    bio = models.CharField(max_length=255, blank=True)
    friends = models.ManyToManyField("Profile", blank=True)
    
    def __str__(self):
        return str(self.user.username)

    def get_absolute_url(self):
        return "/users/{}".format(self.slug)

def post_save_user_model_receiver(sender, instance, created, *args, **kwargs):
    if created:
        try:
            Profile.objects.create(user=instance)
        except:
            pass

post_save.connect(post_save_user_model_receiver, sender=settings.AUTH_USER_MODEL)

class FriendRequest(models.Model):
	to_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='to_user', on_delete=models.CASCADE)
	from_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='from_user', on_delete=models.CASCADE)
	timestamp = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return "From {}, to {}".format(self.from_user.username, self.to_user.username)

users/forms.py
from django import forms
from account.models import User
from users.models import Profile


class UserUpdateForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = User
		fields = ['first_name','last_name', 'email']

class ProfileUpdateForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['bio', 'avatar']

users/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404
from .models import Profile
from feed.models import Post
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from account.models import User
from django.conf import settings
from django.http import HttpResponseRedirect, JsonResponse
from users.models import Profile, FriendRequest
from users.forms import UserUpdateForm, ProfileUpdateForm
import random


@login_required
def users_list(request):
    users = Profile.objects.exclude(user=request.user)
    sent_friend_requests = FriendRequest.objects.filter(from_user=request.user)
    my_friends = request.user.profile.friends.all()
    sent_to = []
    friends = []
    for user in my_friends:
        friend = user.friends.all()
        for f in friend:
            if f in friends:
                friend = friend.exclude(user=f.user)
        friends += friend
    for i in my_friends:
        if i in friends:
            friends.remove(i)
    if request.user.profile in friends:
        friends.remove(request.user.profile)
    random_list = random.sample(list(users), min(len(list(users)), 10))
    for r in random_list:
        if r in friends:
            random_list.remove(r)
    friends += random_list
    for i in my_friends:
        if i in friends:
            friends.remove(i)
    for se in sent_friend_requests:
        sent_to.append(se.to_user)
    context = {
        'users': users,
        'sent': sent_to
    }
    return render(request, "users/users_list.html", context)


def friend_list(request):
    p = request.user.profile
    friends = p.friends.all()
    context = {
        'friends': friends
    }
    return render(request, "users/profile.html", context)


@login_required
def send_friend_request(request, id):
    user = get_object_or_404(User, id=id)
    frequest, created = FriendRequest.objects.get_or_create(
        from_user=request.user,
        to_user=user)
    messages.success(request, 'Friend Request send successfully')
    return HttpResponseRedirect('/users/')


@login_required
def accept_friend_request(request, id):
    from_user = get_object_or_404(User, id=id)
    frequest = FriendRequest.objects.filter(
        from_user=from_user, to_user=request.user).first()
    user1 = frequest.to_user
    user2 = from_user
    user1.profile.friends.add(user2.profile)
    user2.profile.friends.add(user1.profile)
    if(FriendRequest.objects.filter(from_user=request.user, to_user=from_user).first()):
        request_rev = FriendRequest.objects.filter(
            from_user=request.user, to_user=from_user).first()
        request_rev.delete()
    frequest.delete()
    return HttpResponseRedirect('/users/{}'.format(request.user.profile.slug))


@login_required
def profile_view(request, phone):
    p = Profile.objects.filter(slug=phone).first()
    u = p.user
    sent_friend_requests = FriendRequest.objects.filter(from_user=p.user)
    rec_friend_requests = FriendRequest.objects.filter(to_user=p.user)
    user_posts = Post.objects.filter(author=u)

    friends_list = p.friends.exclude(user=request.user)

    # is this user our friend
    button_status = 'none'
    if p not in request.user.profile.friends.all():
        button_status = 'not_friend'

        # if we have sent him a friend request
        if len(FriendRequest.objects.filter(
                from_user=request.user).filter(to_user=p.user)) == 1:
            button_status = 'friend_request_sent'

        # if we have recieved a friend request
        if len(FriendRequest.objects.filter(
                from_user=p.user).filter(to_user=request.user)) == 1:
            button_status = 'friend_request_received'

    context = {
        'u': u,
        'button_status': button_status,
        'friends': friends_list,
        'mfrnd_count': friends_list.count,
        'sent_friend_requests': sent_friend_requests,
        'rec_friend_requests': rec_friend_requests,
        'post_count': user_posts.count
    }

    return render(request, "users/profile.html", context)


@login_required
def my_profile(request):
    p = request.user.profile
    you = p.user
    sent_friend_requests = FriendRequest.objects.filter(from_user=you)
    rec_friend_requests = FriendRequest.objects.filter(to_user=you)
    user_posts = Post.objects.filter(author=you)
    friends = p.friends.all()

    # is this user our friend
    button_status = 'none'
    if p not in request.user.profile.friends.all():
        button_status = 'not_friend'

        # if we have sent him a friend request
        if len(FriendRequest.objects.filter(
                from_user=request.user).filter(to_user=you)) == 1:
            button_status = 'friend_request_sent'

        if len(FriendRequest.objects.filter(
                from_user=p.user).filter(to_user=request.user)) == 1:
            button_status = 'friend_request_received'

    # List of friends
    p = request.user.profile
    friends = p.friends.all()

    context = {
        'u': you,
        'button_status': button_status,
        'friends_list': friends,
        'sent_friend_requests': sent_friend_requests,
        'rec_friend_requests': rec_friend_requests,
        'post_count': user_posts.count,
        'friends': friends
    }

    return render(request, "users/profile.html", context)


@login_required
def search_users(request):
    query = request.GET.get('q')
    friends_list = request.user.profile.friends.all()
    print('\n\n', friends_list)
    users_list = []
    if query:
        users_list = User.objects.filter(first_name__icontains=query) | User.objects.filter(
            last_name__icontains=query) | User.objects.filter(email__icontains=query) | User.objects.filter(phone__icontains=query)

    return render(request, "users/search.html", {'users': users_list, 'friends': friends_list})


def search_api(request):
    query = request.GET.get('q')
    payload = []

    if query:
        q_results = User.objects.filter(first_name__icontains=query) | User.objects.filter(
            last_name__icontains=query) | User.objects.filter(email__icontains=query) | User.objects.filter(phone__icontains=query)

        for result in q_results:
            payload.append(result.first_name)
            payload.append(result.last_name)
            payload.append(result.email)
            payload.append(result.phone)

    return JsonResponse({'status': 200, 'data': payload})

users/templates/users/profile.html
{% extends 'account/home.html' %}
{% load static %}
{% block contents %}


<!-- profile component -->


<div
    class="bg-white my-12 pb-6 w-full justify-center items-center overflow-hidden md:max-w-4xl rounded-lg shadow-sm mx-auto">
    <div class="relative h-40">
        <img class="absolute h-full w-full object-cover"
            src="https://media.istockphoto.com/vectors/hands-holding-smartphones-vector-id1280873974?k=20&m=1280873974&s=612x612&w=0&h=r0i0Rfi52kXoG19ERg-V0eH9FecsBQTzsjzE0n6m_Lw=">
    </div>
    <div class="relative shadow mx-auto h-32 w-32 -my-12 border-white rounded-full overflow-hidden border-4">
        <img class="object-cover w-full h-full" src="{{ u.profile.avatar.url }}">
    </div>
    <div class="mt-16">
        <h1 class="text-lg text-center font-semibold">
            {{u.first_name}} <span class='px-0.5'></span>{{u.last_name}}
        </h1>
        <p class="text-sm text-gray-600 text-center">
            {% if request.user != u %}
            {{mfrnd_count}} friends in common
            {% endif %}
            {{p.bio}}
        </p>
    </div>


    <!-- friend list component -->
    {% if request.user == u %}
    <div class="bg-gray-50 my-12 pb-4 px-4 rounded-md w-full">
        <p class="ml-3 text-bold text-2xl">Friend list</p>
        
        <div class="overflow-x-auto mt-6">
            {% if friends %}
            <table class="table-auto border-collapse w-full">
                <tbody class="text-sm font-normal text-gray-700">
                    {% for user_p in friends %}
                    <tr class="  hover:bg-gray-100 border-b border-gray-200 shadow-md rounded-md py-10">
                        <td class="px-4 py-4 text-md text-bold ">
                            <a href="{{ user_p.get_absolute_url }}"><img src="{{ user_p.avatar.url }}" class="rounded-full w-16 h-16"/></a>
                            
                        </td>
                        <td class="px-4 py-4 text-md text-bold ">
                            
                            <a class=" text-gray-700 text-bold text-xl py-4 px-48 hover:text-blue-600" href="{{ user_p.get_absolute_url }}">{{ user_p.user.first_name }} <span class='pl-1'>{{ user_p.user.last_name }}</span></a>
                        </td>

                    </tr>

                    {% endfor %}
                    {% else %}

                    <tr class="hover:bg-gray-100 border-b border-gray-200 py-10">
                        <td class="px-4 py-4"> <a class="ml-3 text-dark">
                                You dont have any friends, find one <a href="{% url 'users:users_list' %}"
                                    class='text-blue-500 hover:text-blue-700'> here!</a>
                        </td>

                    </tr>


                </tbody>
                {% endif %}
            </table>
        </div>

    </div>
    {% endif %}
    <!--mutual friends component-->
    {% if request.user != u %}
    <div class="bg-gray-50 my-12 pb-4 px-4 rounded-md w-full">
        <p class="ml-3 text-bold text-2xl">Mutule Friends</p>
        
        <div class="overflow-x-auto mt-6">
            {% if friends %}
            {% for user_p in friends %}
            <table class="table-auto border-collapse w-full">
                <tbody class="text-sm font-normal text-gray-700">
                    <tr class="  hover:bg-gray-100 border-b border-gray-200 shadow-md rounded-md py-10">
                        <td class="px-4 py-4 text-md text-bold ">
                            <a href="{{ user_p.get_absolute_url }}"><img src="{{ user_p.avatar.url }}" class="rounded-full w-16 h-16"/></a>
                            
                        </td>
                        <td class="px-4 py-4 text-md text-bold ">
                            
                            <a class=" text-gray-700 text-bold text-xl py-4 px-48 hover:text-blue-600" href="{{ user_p.get_absolute_url }}">{{ user_p.user.first_name }} <span class='pl-1'>{{ user_p.user.last_name }}</span></a>
                        </td>

                    </tr>

                    {% endfor %}
                    {% else %}

                    <tr class="hover:bg-gray-100 border-b border-gray-200 py-10">
                        <td class="px-4 py-4"> <a class="ml-3 text-dark">
                                You dont have any mutule friends, make new friends <a href="{% url 'users:users_list' %}"
                                    class='text-blue-500 hover:text-blue-700'> here!</a>
                        </td>

                    </tr>


                </tbody>
                {% endif %}
            </table>
        </div>

    </div>
    {% endif %}

    <!-- friend Request component -->
    
    {% if u == request.user %}
    <div class="bg-gray-50 my-12 pb-4 px-4 rounded-md w-full">
        <p class="ml-3 text-bold text-2xl">Friend Request's Received!</p>
        <div class="flex justify-between w-full pt-6 ">
            {% if not rec_friend_requests %}
            <p class='ml-3'>No Friend request received!</p>



            {% else %}


            <table class="table-auto border-collapse w-full">

                <tbody class="text-md font-normal text-gray-700">
                    {% for r_request in rec_friend_requests %}
                    <tr class="hover:bg-gray-100 border-b border-gray-200 py-10">
                        <td class="px-4 py-4">
                            <a href="{{ r_request.from_user.profile.get_absolute_url }}"><img
                                    src="{{ r_request.from_user.profile.avatar.url }}" class="rounded full w-16 h-16"
                                    alt="user-frnd-rqst-img" /></a></td>
                        <td class="px-4 py-4"> <a class=""
                                href="{{ r_request.from_user.profile.get_absolute_url }}"><b>{{ r_request.from_user.first_name }}</b>
                            </a></td>
                        <td class="px-4 py-4"><a href="/users/friend-request/accept/{{ r_request.from_user.id }}"
                                class=' px-4 py-2 rounded-md border-1 text-md text-white bg-blue-500 hover:bg-blue-600'>Accept
                            </a>
                        </td>
                        <td class="px-4 py-4"><a href="/users/friend-request/delete/{{ r_request.from_user.id }}"
                                class=' px-4 py-2 rounded-md border-1 text-md text-white bg-red-500 hover:bg-red-600'>Cancel
                            </a></td>

                    </tr>
                    {% endfor %} {% endif %} {% endif %}



                </tbody>
            </table>
        </div>
    </div>
</div>





</div>



</div>




{% endblock contents %}

users/templates/users/search.html
{% extends 'account/home.html' %}

{% block contents %}


<!-- search component -->
<div class="fixed top-0 left-0 w-full h-full bg-gray-200 z-40 select-none">
    <div class="w-4/6 z-50 relative mx-auto mt-36">
      
      <div class="bg-white w-full rounded-xl shadow-xl overflow-hidden p-1">
        <!-- items -->
        {% if users %}
        {% for user in users %}
        <div class="my-2 w-full flex p-3 pl-4 items-center hover:bg-gray-300 rounded-lg cursor-pointer">
            <div class="mr-4"><div class="h-9 w-9 rounded-sm flex items-center justify-center text-3xl mr-12" >
              <img src="{{user.profile.avatar.url}}" alt="" class="rounded-full w-12 h-12  ">
            </div>
          </div>
          <div>
            <div class="font-bold text-lg"> <a href="{% url 'users:profile_view' user.phone %}">{{user.first_name}} {{user.last_name}}</a> </div>
            <div class="text-xs text-gray-500">
              <span class="mr-2">Phone: {{user.phone}}</span>
              <span class="mr-2">email: {{user.email}}</span>
              {% if not user.profile in friends %}
              <a href="{% url 'users:send_friend_request' user.id %}">
                <span class="px-4 py-2 bg-blue-500 border text-white hover:bg-blue-600 rounded-md">add friend</span>
              </a>
              {% else %}
              <a href="">
                <span class="px-4 py-2 bg-red-500 border text-white hover:bg-red-600 rounded-md">un friend</span>
              </a>
              {% endif %}
            </div>
          </div>
        </div>
        
      

        
        
        {% endfor %}
        {% else %}
        <div class="my-2 w-full flex p-3 pl-4 items-center hover:bg-gray-300 rounded-lg">
          No Result found!
        </div>
        {% endif %}

          </div>
        </div>
      </div>
    </div>
  </div>


{% endblock contents %}

users/templates/users/users_list.html
{% extends 'account/home.html' %}
{% load static %}
{% block contents %}
<script src="https://unpkg.com/@trevoreyre/autocomplete-js"></script>
<link
  rel="stylesheet"
  href="https://unpkg.com/@trevoreyre/autocomplete-js/dist/style.css"
/>




<!--alert-message-->
{% if messages %}
{% for message in messages %}
<div class="container" id="alertbox">
    <div class="container w-1/3 mt-20 mx-auto px-auto bg-green-500 rounder-md flex items-center text-white text-sm font-bold px-4 py-3 relative"
        role="alert">
        <svg class="fill-current w-4 h-4 mr-2" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <path
                d="M12.432 0c1.34 0 2.01.912 2.01 1.957 0 1.305-1.164 2.512-2.679 2.512-1.269 0-2.009-.75-1.974-1.99C9.789 1.436 10.67 0 12.432 0zM8.309 20c-1.058 0-1.833-.652-1.093-3.524l1.214-5.092c.211-.814.246-1.141 0-1.141-.317 0-1.689.562-2.502 1.117l-.528-.88c2.572-2.186 5.531-3.467 6.801-3.467 1.057 0 1.233 1.273.705 3.23l-1.391 5.352c-.246.945-.141 1.271.106 1.271.317 0 1.357-.392 2.379-1.207l.6.814C12.098 19.02 9.365 20 8.309 20z" />
        </svg>
        <p>{{message}}</p>

        <span class="absolute top-0 bottom-0 right-0 px-4 py-3 closealertbutton">
            <svg class="fill-current h-6 w-6 text-white" role="button" xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 20 20">
                <title>Close</title>
                <path
                    d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z" />
            </svg>
        </span>
    </div>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"
	integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous">
	</script>

<script>
$(".closealertbutton").click(function (e) {
    // $('.alertbox')[0].hide()
    // e.preventDefault();
    pid = $(this).parent().parent().hide(500)
    console.log(pid)
    // $(".alertbox", this).hide()
})
</script>
{% endfor %}
{% endif %}

<!-- user-list-component -->
<div class=" mx-auto my-12 bg-white border-2 pb-4 px-4 rounded-md w-3/4">
    <div class="flex justify-between mx-auto w-full pt-6 ">
        <p class="ml-3 text-2xl text-bold"> User's List </p>

        <!--user search component-->

<div id="autocomplete" class="  autocomplete">
    <form action="/users/search_users/" method="get" class='flex flex-tem-center'>
        <input type='text' name='Search users' class="autocomplete-input leading-snug border border-gray-300 block w-full appearance-none bg-gray-100 text-sm text-gray-600 py-1 px-4 pl-8 rounded-lg" placeholder='Search For Users'/>
        <ul class="autocomplete-result-list"></ul>
        
    </form>
</div>

<script>
    new Autocomplete('#autocomplete', {
        search : input => {
            console.log(input)
            const url = `/users/search/?q=${input}`
            return new Promise(resolve => {
                fetch(url)
                .then(response => response.json())
                .then(data => {
                    console.log(data)
                    resolve(data.data)
                })
            })
        },
        onSubmit : result => {
            window.open(`../users/search_users/?q=${(result)}`)

        }
    })
</script>


    </div>
    
    <div class="overflow-x-auto mt-6">
        {% if users %}
        <table class="table-auto border-collapse w-full">

            <tbody class="text-sm font-normal text-gray-700">
                {% for user_p in users %}
                <tr class="  hover:bg-gray-100 border-b border-gray-200 shadow-md rounded-md py-10">
                    <td class="px-4 py-4 text-md text-bold ">
                        <a href="{{ user_p.get_absolute_url }}"><img src="{{ user_p.avatar.url }}" class="rounded-full w-16 h-16"/></a>
                        
                    </td>
                    <td class="px-4 py-4 text-md text-bold ">
                        
                        <a class=" text-gray-700 text-bold text-xl py-4 px-48 hover:text-blue-600" href="{{ user_p.get_absolute_url }}">{{ user_p.user.first_name }} <span class='pl-1'>{{ user_p.user.last_name }}</span></a>
                    </td>
                    {% if not user_p.user in sent %}
                    <td class="px-4 py-4 text-md text-bold ">
                        <a class="text-dark" href="{% url 'users:send_friend_request' user_p.user.id %}">
                            <span class='px-6 py-2 bg-blue-500 rounded-md text-white hover:bg-blue-600'>Add friends</span></a>
                        <a href="{{ user_p.get_absolute_url }}"></a>
                    </td>
                    {% else %}
                    <td class="px-4 py-4 text-md text-bold ">
                        <a href="#"><span class='px-4 py-2 bg-red-500 rounded-md text-white hover:bg-red-600 hover:cursor'>Request Send</span></a>
                    </td>
                    {% endif %}
                    {% endfor %}
                </tr>
                

            </tbody>
        </table>
        {% endif %}
    </div>
    <div id="pagination" class="w-full flex justify-center border-t border-gray-100 pt-4 items-center">


    </div>
</div>



{% endblock contents %}